export const startupStages = [
  "Idea",
  "Pre-Seed",
  "Seed",
  "Late-Seed",
  "Series A",
  "Series B",
  "Series B",
  "Series C+",
];

export const industries = [
  "Fintech",
  "Proptech",
  "Software Services & Hardware",
  "E-commerce",
  "Food & Beverage",
  "Mobility & Logistics",
  "Entretainment & Media",
  "Sportstech",
  "Healthtech",
  "Hospitals & Pharmaceutical",
  "Traveltech",
  "Edtech",
  "Agrotech",
  "Cleantech",
  "Energytech",
  "Web 3 & Crypto",
  "Robotics",
  "Smart Cities",
  "Nanotechnology",
  "Biotech",
  "Social Impact",
  "Big Data",
  "IoT",
  "Artificial Intelligence",
  "Cybersecurity",
  "Insuretech",
  "Retail",
  "HRtech",
  "API Infastructure",
  "Minning & Extraction",
];
