export const startupStages = [
  "Idea",
  "Pre-Seed",
  "Seed",
  "Late-Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series C+",
];

export const industries = [
  "Finances",
  "Real State & Construction",
  "Software Services & Hardware",
  "Retail & Commerce",
  "Food & Beverage",
  "Mobility & Logistics",
  "Entretainment & Media",
  "Sports",
  "Health",
  "Hospitals & Pharmaceutical",
  "Travel",
  "Education",
  "Agriculture",
  "Cleantech",
  "Energytech",
  "Web 3 & Crypto",
  "Robotics",
  "Smart Cities",
  "Nanotechnology",
  "Biotech",
  "Social Impact",
  "Big Data",
  "IoT",
  "Artificial Intelligence",
  "Cybersecurity",
  "Insuretech",
  "HRtech",
  "API Infastructure",
  "Minning & Extraction",
];

export const businessModel = [
  "Subscription",
  "Freemium",
  "Licensing",
  "Saas",
  "Advertising",
  "Marketplace",
  "Hardware Selling",
  "Crowdfunding",
  "Usage-Based",
  "Enterprise",
  "E-commerce",
  "Transactional",
];

export const usCorp = [
  "Yes",
  "No",
  "In Progress",
  "I need support to create an LLC, C-Corp, etc.",
];
